package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"math/rand"
	"net"
	"net/url"
	"time"

	"github.com/jackc/pgx/v5"
)

// payload mirrors the JSON document the trigger publishes. Kept minimal on
// purpose: pg_notify payloads are capped at 8000 bytes and this is the whole
// message body.
type verificationPayload struct {
	Email     string `json:"email"`
	Code      string `json:"code"`
	ExpiresAt string `json:"expires_at"`
}

// triggerDDL is a template. Only the channel name is interpolated, and
// loadConfig has already constrained it to ^[a-z_][a-z0-9_]*$, so there is no
// injection path. The table and schema go through pgx.Identifier.Sanitize().
//
// DROP and CREATE run as one multi-statement Exec inside a single implicit
// transaction, so the trigger is never observably absent.
const triggerDDL = `
CREATE OR REPLACE FUNCTION public.notify_multica_verification_code() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
    body text;
BEGIN
    IF NEW.code IS NULL OR NEW.code = '' THEN
        RETURN NEW;
    END IF;
    body := json_build_object(
        'email',      NEW.email,
        'code',       NEW.code,
        'expires_at', to_char(NEW.expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
    )::text;
    PERFORM pg_notify('%s', body);
    RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS %s ON %s;
CREATE TRIGGER %s
    AFTER INSERT ON %s
    FOR EACH ROW EXECUTE FUNCTION public.notify_multica_verification_code();
`

// notifier holds the pieces watch() needs.
type notifier struct {
	cfg *config
	log *slog.Logger
	tg  *telegramClient
}

// connect opens a pgx connection from the discrete PG* settings rather than
// letting pgx parse DATABASE_URL. url.UserPassword does the escaping, so a
// password containing '@' or '/' cannot corrupt the DSN -- which matters here
// because the password is machine-generated by CNPG.
func connect(ctx context.Context, cfg *config) (*pgx.Conn, error) {
	u := &url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(cfg.pgUser, cfg.pgPassword),
		Host:   net.JoinHostPort(cfg.pgHost, cfg.pgPort),
		Path:   "/" + cfg.pgDatabase,
	}
	q := u.Query()
	q.Set("sslmode", cfg.pgSSLMode)
	u.RawQuery = q.Encode()

	// application_name shows up in pg_stat_activity, which makes it obvious in
	// Mimir/Grafana if this ever starts holding connections open.
	cfgCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()
	conn, err := pgx.ConnectConfig(cfgCtx, mustParse(cfg, u.String()))
	if err != nil {
		return nil, fmt.Errorf("connect to %s:%s/%s: %w", cfg.pgHost, cfg.pgPort, cfg.pgDatabase, err)
	}
	return conn, nil
}

func mustParse(cfg *config, dsn string) *pgx.ConnConfig {
	c, err := pgx.ParseConfig(dsn)
	if err != nil {
		// dsn is built from url.URL, so this cannot fail in practice.
		panic(fmt.Sprintf("parse dsn: %v", err))
	}
	c.RuntimeParams["application_name"] = "multica-code-notifier"
	c.ConnectTimeout = 15 * time.Second
	return c
}

func (n *notifier) qualifiedTable() string {
	return pgx.Identifier{n.cfg.tableSchema, n.cfg.table}.Sanitize()
}

func (n *notifier) triggerName() string {
	return pgx.Identifier{"notify_multica_verification_code"}.Sanitize()
}

// installTrigger creates the NOTIFY trigger if it is not already correct.
//
// It takes a transaction-scoped advisory lock so that several replicas racing
// on startup cannot interleave their DROP/CREATE. The lock is best-effort: if
// another replica holds it we assume that replica is doing the work, and the
// DDL is idempotent either way.
func (n *notifier) installTrigger(ctx context.Context, conn *pgx.Conn) error {
	const lockKey = 8421994711 // arbitrary, stable, namespaced by convention

	var locked bool
	if err := conn.QueryRow(ctx, "SELECT pg_try_advisory_xact_lock($1)", lockKey).Scan(&locked); err != nil {
		return fmt.Errorf("advisory lock: %w", err)
	}

	tbl := n.qualifiedTable()
	trg := n.triggerName()
	ddl := fmt.Sprintf(triggerDDL, n.cfg.channel, trg, tbl, trg, tbl)

	tx, err := conn.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin: %w", err)
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, ddl); err != nil {
		return fmt.Errorf("install trigger on %s: %w", tbl, err)
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit trigger: %w", err)
	}

	n.log.Info("trigger installed",
		"table", tbl,
		"channel", n.cfg.channel,
		"advisory_lock_held_by_peer", !locked)
	return nil
}

// watch is the top-level retry loop. Each iteration owns exactly one database
// connection, which is required: LISTEN/NOTIFY is per-session, so a reconnect
// has to re-LISTEN and re-check the trigger.
func (n *notifier) watch(ctx context.Context) error {
	backoff := time.Second

	for {
		err := n.session(ctx)
		if ctx.Err() != nil {
			n.log.Info("shutting down")
			return nil
		}
		if err != nil && errors.Is(err, context.Canceled) {
			return nil
		}

		// Full jitter, capped. Matters here because the multica-database
		// Cluster restart/SPIRE-style blips take down every replica of this
		// program at once and an unpaced retry loop would hammer the database
		// exactly when it is coming back up.
		sleep := time.Duration(rand.Int63n(int64(backoff)))
		n.log.Warn("database session ended, reconnecting",
			"err", err, "retry_in", sleep.Round(time.Millisecond))
		select {
		case <-ctx.Done():
			return nil
		case <-time.After(sleep):
		}

		backoff *= 2
		if backoff > n.cfg.maxBackoff {
			backoff = n.cfg.maxBackoff
		}
	}
}

// session runs until the connection fails.
func (n *notifier) session(ctx context.Context) error {
	conn, err := connect(ctx, n.cfg)
	if err != nil {
		return err
	}
	defer conn.Close(context.WithoutCancel(ctx))

	if err := n.installTrigger(ctx, conn); err != nil {
		return err
	}

	// LISTEN must come after the trigger exists, so the first code requested
	// after startup is already covered.
	if _, err := conn.Exec(ctx, fmt.Sprintf("LISTEN %s", pgx.Identifier{n.cfg.channel}.Sanitize())); err != nil {
		return fmt.Errorf("listen %s: %w", n.cfg.channel, err)
	}
	n.log.Info("listening", "channel", n.cfg.channel, "table", n.qualifiedTable())

	for {
		notification, err := conn.WaitForNotification(ctx)
		if err != nil {
			return fmt.Errorf("wait for notification: %w", err)
		}
		n.handle(ctx, notification.Payload)
	}
}

func (n *notifier) handle(ctx context.Context, payload string) {
	var p verificationPayload
	if err := json.Unmarshal([]byte(payload), &p); err != nil {
		n.log.Error("undecodable notification payload", "err", err, "payload", payload)
		return
	}
	if !n.cfg.allowed(p.Email) {
		n.log.Info("skipping address not on the allowlist", "email", p.Email)
		return
	}

	n.log.Info("new verification code", "email", p.Email, "expires_at", p.ExpiresAt)

	// Notification delivery is synchronous and at-most-once: if Telegram is
	// down the code is lost. Acceptable, because the row is still in the table
	// and Multica's login page will happily mint another one on request.
	if err := n.tg.sendMessage(ctx, formatMessage(p)); err != nil {
		n.log.Error("telegram delivery failed", "err", err, "email", p.Email)
		return
	}
	n.log.Info("code delivered", "email", p.Email)
}
